version: '2'
  
services:

  base:
    build:
      context: .
    image: 'gippy:latest'
    entrypoint: /bin/bash
    env_file: .env
    volumes:
      - '.:/home/geolambda/work'

  test27:
    image: 'gippy:latest'
    entrypoint: bash -c 'python -m pytest test/'
    working_dir: /home/geolambda/test
    env_file: .env
    volumes:
      - './test:/home/geolambda/test'

  test36:
    image: 'gippy:latest'
    entrypoint: bash -c 'python3 -m pytest test/'
    working_dir: /home/geolambda/test
    env_file: .env
    volumes:
      - './test:/home/geolambda/test'
